=== amyjko/bookish/static/schemas/book.json
{
	"$schema": "http://json-schema.org/draft-07/schema#",
	"title": "Bookish book schema",
    "type": "object",
    "definitions": {
        "embed": {
            "type": ["string", "null"],
            "pattern": "^\\|.+\\|.+\\|.+\\|.+\\|$"
        }
    },
	"required": [
        "title", "authors", "description",
        "chapters", "revisions", "license", "sources", "references",
        "images"
    ],
    "additionalProperties": false,
	"properties": {
        "title": { "type": "string" },
        "authors": {
            "type": "array",
            "items": { "type": "string" }
        },
        "images": {
            "type": "object",
            "properties": {
                "cover": { "$ref": "#/definitions/embed" },
                "unknown": { "$ref": "#/definitions/embed" },
                "index": { "$ref": "#/definitions/embed" },
                "references": { "$ref": "#/definitions/embed" },
                "glossary": { "$ref": "#/definitions/embed" },
                "search": { "$ref": "#/definitions/embed" }
            }    
        },
        "description": { "type": "string" },
        "acknowledgements": { "type": "string" },
        "chapters": {
            "type": "array",
            "items": {
                "type": "object",
                "required": ["id", "title", "image"],
                "properties": {
                    "id": { "type": "string", "pattern": "^[a-zA-Z0-9]+$"},
                    "title": { "type": "string" },
                    "image": { "$ref": "#/definitions/embed" },
                    "numbered": { "type": "boolean", "default": "True by default" },
                    "section": { "type": "string" },
                    "authors": { "type": "array", "items": { "type": "string" }},
                    "forthcoming": { "type": "boolean" }
                }
            }
        },
        "revisions": {
            "type": "array",
            "items": {
                "type": "array",
                "minItems": 2,
                "maxItems": 2,
                "items": { "type": "string" }
            }
        },
        "tags": { 
            "type": "array",
            "items": { "type": "string" }
        },
        "license": { "type": "string" },
        "sources": { "type": "object", "additionalProperties": { "type": "string" } },
        "references": {
            "type": "object",
            "additionalProperties": {
                "oneOf": [
                    { "type": "string" },
                    {
                        "type": "array",
                        "maxItems": 6,
                        "items": [
                            { "type": "string" },
                            { "type": "integer"},
                            { "type": "string" },
                            { "type": "string" },
                            { "type": ["string", "null"], "format": "uri" }
                        ],
                        "additionalItems": { "type": "string" }
                    }
                ]
            }
        },
        "symbols": {
            "type": "object",
            "additionalProperties": { "type": "string" }
        },
        "glossary": {
            "type": "object",
            "additionalProperties": {
                "type": "object",
                "properties": {
                    "phrase": { "type": "string" },
                    "definition": { "type": "string" },
                    "synonyms": { "type": "array", "items": { "type": "string" }}
                },
                "additionalProperties": false,
                "required": ["phrase", "definition"]
            }
        }
    }
}

=== amyjko/bookish/static/examples/tutorial/book.json
{
	"title": "Bookish Tutorial: An placeholder for better documentation",
	"authors": [
		"[Amy J. Ko|https://faculty.washington.edu/ajko]",
		"Boomy"
	],
	"images": {
		"cover": "|cover.jpg|A photograph of Boomy the cat sleeping|Boomy is excited that you're trying Bookish!|@amyCredit|",
		"search": "|cover.jpg|A photograph of Boomy the cat sleeping|Boomy's looking for something...|@amyCredit|",
		"media": "|cover.jpg|A photograph of Boomy the cat sleeping|Boomy's looking for something...|@amyCredit|",
		"glossary": "|cover.jpg|A photograph of Boomy the cat looking skeptical.|Boomy doesn't know what you mean.|@amyCredit|",
		"references": "|cover.jpg|A photograph of Boomy the cat sleeping|Boomy has some books for you!|@amyCredit|",
		"index": "|cover.jpg|A photograph of Boomy the cat sleeping|Boomy's wondering what word you're curious about!|@amyCredit|",
		"unknown": "|unknown.jpg|A photograph of Boomy the cat looking skeptical.|Boomy is worried that you're lost.|@amyCredit|"
	},
	"description": "This is an example book, intended for presentation with the Bookish framework. Don't let it's simplicity fool you: it demonstrates all of the features of Bookish, so you should be able to copy and modify any of its content to help you write your book.",
	"acknowledgements": "Thanks to Boomy for all her hard work.",
	"chapters": [
		{
			"id": "introduction",
			"title": "Introduction",
			"authors": ["Someone Else"],
			"image": "|chapter1.jpg|A photo of Boomy|OMG this is the longest caption ever OMG this is the longest caption ever OMG this is the longest caption ever OMG this is the longest caption ever OMG this is the longest caption ever OMG this is the longest caption ever |@amyCredit|",
			"numbered": true
		},
		{
			"id": "marginals",
			"title": "Marginals",
			"image": "|unknown.jpg|A photo of skeptical Boomy|Time to learn about errors, huh?|@amyCredit|"
		},
		{
			"id": "unfinished",
			"title": "Unfinished",
			"image": "|unknown.jpg|A photo of skeptical Boomy|Time to learn about errors, huh?|@amyCredit|",
			"section": "Part II",
			"forthcoming": true,
			"numbered": false
		},
		{
			"id": "errors",
			"title": "Errors",
			"image": "|unknown.jpg|A photo of skeptical Boomy|Time to learn about errors, huh?|@amyCredit|",
			"section": "Part I"
		}
	],
	"tags": [ "draft" ],
	"revisions": [
		["August 30th, 2020", "Created the initial draft."]
	],
	"license": "[Creative Commons Attribution-NoDeriviatives 4.0|https://creativecommons.org/licenses/by-nd/4.0/]",
	"sources": {
		"ICER": "ACM International Computing Education Research Conference (ICER)"
	},
	"references": {
		"swearngin20": "Amanda Swearngin, Chenglong Wang, Alannah Oleson, James Fogarty, Amy J. Ko (2020). [Scout: Rapid Exploration of Interface Layout Alternatives through High-Level Design Constraints|http://faculty.washington.edu/ajko/papers/Swearngin2020Scout.pdf]. _ACM SIGCHI Conference on Human Factors in Computing Systems_ (CHI), 1-13.",
		"latoza20": "Thomas D. LaToza, Maryam Arab, Dastyni Loksa, Amy J. Ko (2020). [Explicit Programming Strategies|http://faculty.washington.edu/ajko/papers/Latoza2020ExplicitProgrammingStrategies.pdf]. Empirical Software Engineering.",
		"register20": [
			"Yim Register, Amy J. Ko", 
			2020,
			"Learning machine learning with personal data helps stakeholders ground advocacy arguments in model mechanics",
			"#ICER", 
			"http://faculty.washington.edu/ajko/papers/Register2020PersonalData.pdf",
			"Finds that teaching machine learning by tracing an algorithm with learners' personal data increases the extent to which they can identify bias in self-advocacy arguments."
		],
		"druga21": "Stefania Druga, Amy J. Ko (2021). How Do Childrenâ€™s Perceptions of Machine Intelligence Change when Training & Coding Smart Programs? ACM Interaction Design for Children.",
		"jds": "jdskfljsakdfjkdlsfj"
	},
	"symbols": {
		"amyCredit": "Amy J. Ko",
		"hello": "Hi, I am _symbolic_ text."
	},
	"glossary": {
		"gloss": {
			"phrase": "glossary",
			"definition": "An alphabetical list of *terms* or _words_ found in or relating to a specific subject, text, or dialect, with explanations; a brief dictionary.",
			"synonyms": ["dictionary"]
		},
		"mouse": {
			"phrase": "mouse",
			"definition": "A cute little mammal."
		}
	}
}
